// apps/react/src/components/square/Square.tsx
import React, { FunctionComponent, memo } from 'react';
import { log } from 'common';

export const Square: FunctionComponent<Props> = ({ onClick, item }) => {
  const emitOnClick = () => {
    onClick(item);
  };
  log('[Render]', item.index);
  return <div className="square" onClick={emitOnClick}>{item.value}</div>;
};

export const SquareWithMemo = memo(Square);

export type SquareItem = { index: string, value: string };

type Props = {
  onClick: (item: SquareItem) => void;
  item: SquareItem;
}

// apps/vue/src/components/Square.vue
<script lang="ts">
import { defineComponent, h } from 'vue';
import { log, SquareItem } from 'common';

export default defineComponent({
  props: {
    item: Object as () => SquareItem,
  },

  render() {
    log('[Render]', this.item?.index);
    return h('div', {
      class: 'square',
      onClick: () => {
        this.$emit('square-click', this.item);
      },
    }, this.item?.value);
  },
});
</script>
